export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const NEWS_HAS_ERRORED = 'NEWS_HAS_ERRORED';
export const NEWS_IS_LOADING = 'NEWS_IS_LOADING';
export const NEWS_GET_DATA_SUCCESS = 'NEWS_GET_DATA_SUCCESS';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';