RSS:
    path: /api/RSS/
    controller: App\Controller\Api\RSS::index

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

api:
  prefix: /api
  resource: "../src/Controller/Api"

api_auth_login:
  path: /api/auth/login
  methods: [POST]

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }


